/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author alessandro
 */
public class inicialGerente extends javax.swing.JFrame {

    /** Creates new form inicialGerente */
    public inicialGerente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sftwName = new javax.swing.JLabel();
        saHoteis = new javax.swing.JLabel();
        iGrBTCadastroCliente = new javax.swing.JButton();
        iGrTitle = new javax.swing.JLabel();
        iGrBTCadastroFuncionario = new javax.swing.JButton();
        iGrBTConsultaCliente = new javax.swing.JButton();
        iGrBTConsultaFuncionario = new javax.swing.JButton();
        iGrBTConsultaQuarto = new javax.swing.JButton();
        iGrBTCheckIn = new javax.swing.JButton();
        iGrBTCheckOut = new javax.swing.JButton();
        iGrBTlogout = new javax.swing.JButton();
        iGrBTHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sftwName.setFont(new java.awt.Font("Enter The Grid", 0, 16)); // NOI18N
        sftwName.setText("Hotel Manager v1.0");

        saHoteis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        iGrBTCadastroCliente.setText("Cadastro de cliente");

        iGrTitle.setFont(new java.awt.Font("Dual-300", 0, 36)); // NOI18N
        iGrTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iGrTitle.setText("Selecione a opção desejada:");

        iGrBTCadastroFuncionario.setText("Cadastro de funcionário");

        iGrBTConsultaCliente.setText("Consulta de cliente");

        iGrBTConsultaFuncionario.setText("Consulta de funcionário");

        iGrBTConsultaQuarto.setText("Consulta de quartos");

        iGrBTCheckIn.setText("Check-in");

        iGrBTCheckOut.setText("Check-out");

        iGrBTlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign_out2.png"))); // NOI18N

        iGrBTHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iGrTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iGrBTCadastroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTCadastroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTConsultaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTConsultaFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTConsultaQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTCheckIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGrBTCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sftwName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saHoteis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iGrBTHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iGrBTlogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sftwName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saHoteis))
                    .addComponent(iGrBTlogout)
                    .addComponent(iGrBTHelp))
                .addGap(18, 18, 18)
                .addComponent(iGrTitle)
                .addGap(53, 53, 53)
                .addComponent(iGrBTCadastroCliente)
                .addGap(26, 26, 26)
                .addComponent(iGrBTCadastroFuncionario)
                .addGap(26, 26, 26)
                .addComponent(iGrBTConsultaCliente)
                .addGap(26, 26, 26)
                .addComponent(iGrBTConsultaFuncionario)
                .addGap(26, 26, 26)
                .addComponent(iGrBTConsultaQuarto)
                .addGap(26, 26, 26)
                .addComponent(iGrBTCheckIn)
                .addGap(26, 26, 26)
                .addComponent(iGrBTCheckOut)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicialGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iGrBTCadastroCliente;
    private javax.swing.JButton iGrBTCadastroFuncionario;
    private javax.swing.JButton iGrBTCheckIn;
    private javax.swing.JButton iGrBTCheckOut;
    private javax.swing.JButton iGrBTConsultaCliente;
    private javax.swing.JButton iGrBTConsultaFuncionario;
    private javax.swing.JButton iGrBTConsultaQuarto;
    private javax.swing.JButton iGrBTHelp;
    private javax.swing.JButton iGrBTlogout;
    private javax.swing.JLabel iGrTitle;
    private javax.swing.JLabel saHoteis;
    private javax.swing.JLabel sftwName;
    // End of variables declaration//GEN-END:variables

}
