/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author alessandro
 */
public class inicialAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form inicialAdministrador
     */
    public inicialAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sftwName = new javax.swing.JLabel();
        saHoteis = new javax.swing.JLabel();
        iAdmTitle = new javax.swing.JLabel();
        iAdmBTCadastroCliente = new javax.swing.JButton();
        iAdmBTCadastroFuncionario = new javax.swing.JButton();
        iAdmBTConsultaCliente = new javax.swing.JButton();
        iAdmBTConsultaFuncionario = new javax.swing.JButton();
        iAdmBTConsultaQuarto = new javax.swing.JButton();
        iAdmBTCheckIn = new javax.swing.JButton();
        iAdmBTCheckOut = new javax.swing.JButton();
        iAdmBTFaq = new javax.swing.JButton();
        iAdmBTResetSenha = new javax.swing.JButton();
        iAdmBTHelp = new javax.swing.JButton();
        iAdmBTlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sftwName.setFont(new java.awt.Font("Enter The Grid", 0, 16)); // NOI18N
        sftwName.setText("Hotel Manager v1.0");

        saHoteis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        iAdmTitle.setFont(new java.awt.Font("Dual-300", 0, 36)); // NOI18N
        iAdmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iAdmTitle.setText("Selecione a opção desejada:");

        iAdmBTCadastroCliente.setText("Cadastro de cliente");

        iAdmBTCadastroFuncionario.setText("Cadastro de funcionário");
        iAdmBTCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAdmBTCadastroFuncionarioActionPerformed(evt);
            }
        });

        iAdmBTConsultaCliente.setText("Consulta de cliente");

        iAdmBTConsultaFuncionario.setText("Consulta de funcionário");

        iAdmBTConsultaQuarto.setText("Consulta de quartos");

        iAdmBTCheckIn.setText("Check-in");

        iAdmBTCheckOut.setText("Check-out");

        iAdmBTFaq.setText("FAQ");

        iAdmBTResetSenha.setText("Reset de Senha");

        iAdmBTHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help2.png"))); // NOI18N

        iAdmBTlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign_out2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iAdmTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iAdmBTCadastroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTCadastroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTConsultaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTConsultaFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTConsultaQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTCheckIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTFaq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAdmBTResetSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saHoteis)
                            .addComponent(sftwName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(660, 660, 660)
                        .addComponent(iAdmBTHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iAdmBTlogout)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sftwName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saHoteis))
                    .addComponent(iAdmBTlogout)
                    .addComponent(iAdmBTHelp))
                .addGap(18, 18, 18)
                .addComponent(iAdmTitle)
                .addGap(53, 53, 53)
                .addComponent(iAdmBTCadastroCliente)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTCadastroFuncionario)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTConsultaCliente)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTConsultaFuncionario)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTConsultaQuarto)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTCheckIn)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTCheckOut)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTFaq)
                .addGap(26, 26, 26)
                .addComponent(iAdmBTResetSenha)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iAdmBTCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAdmBTCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAdmBTCadastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicialAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iAdmBTCadastroCliente;
    private javax.swing.JButton iAdmBTCadastroFuncionario;
    private javax.swing.JButton iAdmBTCheckIn;
    private javax.swing.JButton iAdmBTCheckOut;
    private javax.swing.JButton iAdmBTConsultaCliente;
    private javax.swing.JButton iAdmBTConsultaFuncionario;
    private javax.swing.JButton iAdmBTConsultaQuarto;
    private javax.swing.JButton iAdmBTFaq;
    private javax.swing.JButton iAdmBTHelp;
    private javax.swing.JButton iAdmBTResetSenha;
    private javax.swing.JButton iAdmBTlogout;
    private javax.swing.JLabel iAdmTitle;
    private javax.swing.JLabel saHoteis;
    private javax.swing.JLabel sftwName;
    // End of variables declaration//GEN-END:variables
}
