/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

/**
 *
 * @author Ramon
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Model
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        title = new javax.swing.JLabel();
        baseboard = new javax.swing.JLabel();
        titleLogin = new javax.swing.JLabel();
        LoginField = new javax.swing.JTextField();
        titlePassword = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Record v1.0");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Start Screen");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${}"), title, org.jdesktop.beansbinding.BeanProperty.create("horizontalAlignment"));
        bindingGroup.addBinding(binding);

        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 150, 1020, -1));

        baseboard.setBackground(new java.awt.Color(0, 0, 0));
        baseboard.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        baseboard.setForeground(new java.awt.Color(255, 255, 255));
        baseboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baseboard.setText("COPYRIGHT - 2016 - Developed by Ramon Santos");
        baseboard.setOpaque(true);
        getContentPane().add(baseboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1024, 30));

        titleLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogin.setText("Login");
        getContentPane().add(titleLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 180, -1));

        LoginField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LoginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 224, 30));

        titlePassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePassword.setText("Password");
        getContentPane().add(titlePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, -1));
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 224, 30));

        LoginButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 224, 30));

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallpaper.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 720));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel baseboard;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLogin;
    private javax.swing.JLabel titlePassword;
    private javax.swing.JLabel wallpaper;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
