/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

/**
 *
 * @author Ramon
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form Model
     */
    public telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseboard = new javax.swing.JLabel();
        SearchField = new javax.swing.JPasswordField();
        Search = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenu();
        NewMovie = new javax.swing.JMenuItem();
        NewGames = new javax.swing.JMenuItem();
        NewSeries = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        EditMovie = new javax.swing.JMenuItem();
        EditGames = new javax.swing.JMenuItem();
        EditSeries = new javax.swing.JMenuItem();
        Collection = new javax.swing.JMenu();
        Top20 = new javax.swing.JMenuItem();
        AdvancedSearch = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AllMovies = new javax.swing.JMenuItem();
        DVD = new javax.swing.JMenuItem();
        BluRay = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        AllGames = new javax.swing.JMenuItem();
        PC = new javax.swing.JMenuItem();
        PS3 = new javax.swing.JMenuItem();
        NewReleases = new javax.swing.JMenu();
        NewReleasesMovies = new javax.swing.JMenuItem();
        NewReleasesGames = new javax.swing.JMenuItem();
        NewReleasesSeries = new javax.swing.JMenuItem();
        Ratings = new javax.swing.JMenu();
        Account = new javax.swing.JMenu();
        AccountSettings = new javax.swing.JMenuItem();
        AccountPassword = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        ViewHelp = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Record v1.0");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseboard.setBackground(new java.awt.Color(0, 0, 0));
        baseboard.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        baseboard.setForeground(new java.awt.Color(255, 255, 255));
        baseboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baseboard.setText("COPYRIGHT - 2016 - Developed by Ramon Santos");
        baseboard.setOpaque(true);
        getContentPane().add(baseboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1024, 30));
        getContentPane().add(SearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 224, 30));

        Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search.setText("Search");
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 90, 30));

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallpaper.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 720));

        File.setText("File");

        New.setText("New");

        NewMovie.setText("Movie");
        New.add(NewMovie);

        NewGames.setText("Games");
        New.add(NewGames);

        NewSeries.setText("Series");
        New.add(NewSeries);

        File.add(New);
        File.add(jSeparator1);

        Exit.setText("Exit");
        File.add(Exit);

        Menu.add(File);

        Edit.setText("Edit");

        EditMovie.setText("Movie");
        Edit.add(EditMovie);

        EditGames.setText("Games");
        Edit.add(EditGames);

        EditSeries.setText("Series");
        Edit.add(EditSeries);

        Menu.add(Edit);

        Collection.setText("Collection");

        Top20.setText("Top 20");
        Collection.add(Top20);

        AdvancedSearch.setText("Advanced Search");
        Collection.add(AdvancedSearch);
        Collection.add(jSeparator2);

        AllMovies.setText("All Movies");
        Collection.add(AllMovies);

        DVD.setText("DVD");
        Collection.add(DVD);

        BluRay.setText("Blu-Ray");
        Collection.add(BluRay);
        Collection.add(jSeparator3);

        AllGames.setText("All Games");
        Collection.add(AllGames);

        PC.setText("PC");
        Collection.add(PC);

        PS3.setText("PS3");
        Collection.add(PS3);

        Menu.add(Collection);

        NewReleases.setText("New Releases");

        NewReleasesMovies.setText("Movies");
        NewReleases.add(NewReleasesMovies);

        NewReleasesGames.setText("Games");
        NewReleases.add(NewReleasesGames);

        NewReleasesSeries.setText("Series");
        NewReleases.add(NewReleasesSeries);

        Menu.add(NewReleases);

        Ratings.setText("Ratings");
        Menu.add(Ratings);

        Account.setText("Account");

        AccountSettings.setText("Settings");
        Account.add(AccountSettings);

        AccountPassword.setText("Password");
        Account.add(AccountPassword);

        Menu.add(Account);

        Help.setText("Help");

        ViewHelp.setText("View Help");
        Help.add(ViewHelp);
        Help.add(jSeparator4);

        About.setText("About");
        Help.add(About);

        Menu.add(Help);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu Account;
    private javax.swing.JMenuItem AccountPassword;
    private javax.swing.JMenuItem AccountSettings;
    private javax.swing.JMenuItem AdvancedSearch;
    private javax.swing.JMenuItem AllGames;
    private javax.swing.JMenuItem AllMovies;
    private javax.swing.JMenuItem BluRay;
    private javax.swing.JMenu Collection;
    private javax.swing.JMenuItem DVD;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem EditGames;
    private javax.swing.JMenuItem EditMovie;
    private javax.swing.JMenuItem EditSeries;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu New;
    private javax.swing.JMenuItem NewGames;
    private javax.swing.JMenuItem NewMovie;
    private javax.swing.JMenu NewReleases;
    private javax.swing.JMenuItem NewReleasesGames;
    private javax.swing.JMenuItem NewReleasesMovies;
    private javax.swing.JMenuItem NewReleasesSeries;
    private javax.swing.JMenuItem NewSeries;
    private javax.swing.JMenuItem PC;
    private javax.swing.JMenuItem PS3;
    private javax.swing.JMenu Ratings;
    private javax.swing.JButton Search;
    private javax.swing.JPasswordField SearchField;
    private javax.swing.JMenuItem Top20;
    private javax.swing.JMenuItem ViewHelp;
    private javax.swing.JLabel baseboard;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
